### ISSUE TITLE
VCard Module is not working in HumHub 1.12

### ISSUE THREAD

**Issue by ralfblask** [humhub-contrib/popover-vcard#14]
@luke- The VCard Module is not working in HumHub 1.12

![image](https://user-images.githubusercontent.com/31233456/182842212-d682dede-4daa-497b-bf67-77baf15972f6.png)

**Comment by classan-eu** [comment]
same for me

**Comment by luke-** [comment]
We're working on an updated version.

Reason: with v1.12 we upgraded the used Twig Library from v1 to v3.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub-contrib/popover-vcard/pull/15.
