### ISSUE TITLE
Twig SecurityPolicy resulting in HTTP/500

### ISSUE THREAD

**Issue by dantefromhell** [humhub-contrib/popover-vcard#18]
I have been using the following twig template for a while
```
{% if profile.tagline %}
        <b>{{ profile.tagline|e }}</b>
{% endif %}
{% if profile.url %}
        <br>
        <a href="{{ profile.url|e }}">{{ profile.url|e }}</a>
{% endif %}
{% if profile.about %}
        <hr style="height:0px; border-style: none;color:white;">
        {{ profile.about|e }}
{% endif %}
```
but since upgrading to version `1.1.3` I recognized some overlays not being displayed.

The `tagline` `url` and `about` fields are all configured as optional (aka the checkbox for `Required` is unticked).

When triggering the vcard popover on user profiles that have not set either `tagline` or `url` the following `HTTP/500` error gets triggered:
```
Exception 'Twig\Sandbox\SecurityNotAllowedMethodError' with message 'Calling "tagline" method on a "humhub\modules\user\models\Profile" object is not allowed in "__string_template__a467a3e9ae0b262d4779e45ef3cd9950" at line 1.' 

in /var/www/localhost/htdocs/protected/vendor/twig/twig/src/Sandbox/SecurityPolicy.php:106

Stack trace:
#0 /var/www/localhost/htdocs/protected/vendor/twig/twig/src/Extension/SandboxExtension.php(84): Twig\Sandbox\SecurityPolicy->checkMethodAllowed()
#1 /var/www/localhost/htdocs/protected/vendor/twig/twig/src/Extension/CoreExtension.php(1629): Twig\Extension\SandboxExtension->checkMethodAllowed()
#2 /var/www/localhost/htdocs/protected/vendor/twig/twig/src/Environment.php(361) : eval()'d code(39): twig_get_attribute()
#3 /var/www/localhost/htdocs/protected/vendor/twig/twig/src/Template.php(394): __TwigTemplate_88fa12bd176cd8ff3b3b090bcac31915->doDisplay()
#4 /var/www/localhost/htdocs/protected/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#5 /var/www/localhost/htdocs/protected/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#6 /var/www/localhost/htdocs/protected/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render()
#7 /var/www/localhost/htdocs/protected/modules/popover-vcard/widgets/VCardUser.php(43): Twig\TemplateWrapper->render()
#8 /var/www/localhost/htdocs/protected/humhub/components/Widget.php(63): humhub\modules\popovervcard\widgets\VCardUser->run()
#9 /var/www/localhost/htdocs/protected/modules/popover-vcard/controllers/IndexController.php(64): humhub\components\Widget::widget()
#10 [internal function]: humhub\modules\popovervcard\controllers\IndexController->actionLoad()
#11 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#12 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#13 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#14 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#15 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#16 /var/www/localhost/htdocs/index.php(25): yii\base\Application->run()
#17 {main}
```

The error is not triggered for empty `about` fields.

## Workaround
This issue was introduced in https://github.com/humhub-contrib/popover-vcard/commit/9077f70c400067999734a3ed181be28fa3d49149 and/ or https://github.com/humhub-contrib/popover-vcard/commit/4bca07f38158c8e53b383ec1e4191d0b930f8cc5, 
commenting https://github.com/humhub-contrib/popover-vcard/blob/master/widgets/VCardUser.php#L37 is a workaround.

Another workaround is adding the fields `tagline` and `url` to `[Profile::class => 'about']`, which IMO defeats the purpose of being able to configure the popover via twig.

## Additional comments
For my use-case limiting the twig filters to `escape` only makes my code more complex. E.g. the line for creating a link could be simplified with the `format` filter and I would love to have access to filters like `trim`.
I'm not sure this could be best implemented, but the current limit in the twig SecurityPolicy makes the module almost unusable beyond the configuration it is shipped with.

**Comment by luke-** [comment]
Seems we need to whitelist all Profile fields here:
https://github.com/humhub-contrib/popover-vcard/blob/master/widgets/VCardUser.php#L37

@yurabakhtin Can you please take a look?

**Comment by Gilbertdelyon** [comment]
May be related to same issue
Vcard  1.1.3
Here under our VCard setting
```
<b>A propos:</b>
{% if profile.about %}
	{{ profile.about |e }}
{% else %}
	Aucune description.
{% endif %}
<br>
<b>Gamertag MSFS:</b>
{% if profile.gamertagmsfs  %}   
     {{ profile.gamertagmsfs|e }}      
{% else %}
       Aucun gamertag MSFS défini
{% endif %}
```
gametagmsfs is configured as follows:
![image](https://github.com/humhub-contrib/popover-vcard/assets/91057837/2dd5f596-89f3-46b3-a7ed-850328f31d81)

**And now the issue:**
When `gamertagmsfs` field is populated it works as expected :)
But when `gamertagmsfs` field is empty **it doesn't work :((**. Vcard is not displayed at all + error log:

`Twig\Sandbox\SecurityNotAllowedMethodError: Calling "gamertagmsfs" method on a "humhub\modules\user\models\Profile" object is not allowed in "__string_template__fd346f6ee436482c286eb4b08664fa0e" at line 9. in /homepages/40/d507972891/htdocs/newdeclicfly/protected/vendor/twig/twig/src/Sandbox/SecurityPolicy.php:105`

This behaviour is strange because it works when native "About" field is empty

**Comment by Gilbertdelyon** [comment]
BTW,
Another strange thing 
As explained in my previous post, Vcard works when field is populated, and doesn't work when field is empty.
So I decided to set a default value, so that the field will always be populated.
Result: it doesn't work :((

**Comment by Gilbertdelyon** [comment]
Just to complete the workaround in @dantefromhell [first post](https://github.com/humhub-contrib/popover-vcard/issues/18#issue-2080800999)
If you need some more fields in your vcard 
Edit `yourhhsite/protected/modules/popover-vcard/widgets/VCardUser.php`
go to line 37
change `[Profile::class => 'about'] `to `[Profile::class => ['about', 'otherprofilefield1', 'otherprofilefield2']]`
I hope this temporary workaround can help.
And thanks to @dantefromhell. You saved my day!
