### ISSUE TITLE
A little bug - Translation variable

### ISSUE THREAD

**Issue by FernandoHCFaria** [humhub-contrib/popover-vcard#26]
File: popover-vcard/widgets/views/vcard-user.php

Line: 35

Change:
`<?= Html::a(Yii::t('MailModule.base', 'Send message'), ['/mail/mail/create', 'ajax' => 1, 'userGuid' => $user->guid], ['class' => 'btn btn-primary btn-sm', 'data-target' => '#globalModal']); ?>
`

To:
`<?= Html::a(Yii::t('MailModule.base', 'Message'), ['/mail/mail/create', 'ajax' => 1, 'userGuid' => $user->guid], ['class' => 'btn btn-primary btn-sm', 'data-target' => '#globalModal']); ?>`

**Comment by luke-** [comment]
Should be released with the latest version 1.1.6

Maybe it's necessary to add the translation on our translation site.
