### ISSUE TITLE
Open profile/space link not working

### ISSUE THREAD

**Issue by buddh4** [humhub-contrib/popover-vcard#4]
Open profile/space links to `index.php?r=&cguid=124b221b-786f-4789-beac-dc8a4f7c6961`

**Comment by berlinonline2** [comment]
Following files/lines have to be changed to fix the problem

### 1. Correct the link for the profile

File: protected\modules\popover-vcard\widgets\views\vcard-user.php
Change line: 38 
from: <a href="<?= Url::to(['/', 'container' => $user]); ?>"
to: <a href="<?= Url::to(['/user/profile', 'container' => $user]); ?>"

### 2. Correct the link for the profile

File:  protected\modules\popover-vcard\widgets\views\vcard-space.php
Change line: 39
from: <a href="<?= Url::to(['/', 'container' => $space]); ?>"
to: <a href="<?= Url::to(['/space/space', 'container' => $space]); ?>"
