### ISSUE TITLE
From my point of view it is not  crystal clear what this modules does

### ISSUE THREAD

**Issue by MasterMindNET** [humhub-contrib/popover-vcard#8]
Please could you enhance README.md?

It would be more comprehensive to be described like `To see the popover you need to hover over a user or space link in a post or somewhere else`

![image](https://user-images.githubusercontent.com/22347676/88399308-5c60e600-cdcf-11ea-8c10-0a0807dd3d3a.png)

**Comment by luke-** [comment]
@Semir1212 Can you take a look at the texts & PR and improve it a bit?

**Comment by luke-** [comment]
https://github.com/humhub-contrib/popover-vcard/commit/b1e389be36c14020c3fbd2029525d5dc73d38c71
